### ISSUE TITLE
"TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by wbashir** [mcrowson/zappa-hug-example#2]
Running into a `TypeError: 'NoneType' object is not callable` when I deploy and hit the Zappa URL fro this repo. Have you run into this before?

**Comment by mcrowson** [comment]
There is likely some package that it is referencing but not able to load. Make sure the virtual environment you’re running Zappa from has all the requirements needed

**Comment by wbashir** [comment]
Once again. Thanks for your help!
